name: Update UFL Standings
on:
  schedule:
    - cron: "30 0-2,8-23 * 3-6 0,6"
    - cron: "0 4 3 1,2,7-12 6"
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas
          python -m pip install pyarrow
          python -m pip install requests
          python -m pip install tqdm
          python -m pip install bs4
          python -m pip install lxml
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run Python Script
        run: |
          python get_ufl_standings.py --save_csv --save_parquet --save_json

      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "standings/current_standings/*.*"
          branches: "main"
          #update_latest_release: true
          overwrite: true
          verbose: true
          default_release_name: "UFL Standings"
      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "standings/weekly_standings/*.*"
          branches: "main"
          #update_latest_release: true
          overwrite: true
          verbose: true
          default_release_name: "UFL Weekly Standings"